name: Build fvm
on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 * * 0' 
env:
  FVM_IMAGE: ghcr.io/kingwill101/fvm
  FVM_VERSION: 3.1.4
jobs:
  push-linkboard-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter-version: [3.19.3, 3.19.6, 3.22.1]
    permissions:
      contents: read
      packages: write
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: fvm
          push: true
          build-args: |
            FLUTTER_VERSION=${{ matrix.flutter-version }}
            FVM_VERSION=${{env.FVM_VERSION}}
          tags: |
            ${{ env.FVM_IMAGE }}:${{ matrix.flutter-version }}
            ${{ env.FVM_IMAGE }}:latest